<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CompactMPC</RootNamespace>
    <AssemblyName>CompactMPC</AssemblyName>
    <AssemblyVersion>0.9.0</AssemblyVersion>
    <Title>CompactMPC</Title>
    <Authors>Jonas Nagy-Kuhlen</Authors>
    <Description>Lightweight Library for Secure Multi-Party Computation in C#</Description>
    <Copyright>Copyright © 2026 Jonas Nagy-Kuhlen</Copyright>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  
</Project>
